backend/controllers/VehicleTypesController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\VehicleTypes;
use common\models\VehicleTypesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\components\AdminCoreController;
use common\components\Common;
use yii\helpers\ArrayHelper;
use common\models\VehicleCharges;
use common\models\VehicleTypeRates;
/**
 * VehicleTypesController implements the CRUD actions for VehicleTypes model.
 */
class VehicleTypesController extends AdminCoreController
{
    /**
     * {@inheritdoc}
     */


    /**
     * Lists all VehicleTypes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VehicleTypesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single VehicleTypes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new VehicleTypes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VehicleTypes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::getAlias('@vehicle_type_create'));
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing VehicleTypes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
               Yii::$app->session->setFlash('success', Yii::getAlias('@vehicle_type_update'));
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing VehicleTypes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
           Yii::$app->session->setFlash('success', Yii::getAlias('@vehicle_type_delete'));
        return $this->redirect(['index']);
    }
     public function actionAddRates($type_id)
    {

        $this->layout = 'popup';
        //GET PROJECT NAME BY PROJECT ID
            $snVehicleTypeName = VehicleTypes::find()->where("id=$type_id")->one();
            $arrVehicleCharges = ArrayHelper::map(VehicleCharges::find()->asArray()->all(), 'id', 'label');
            $vehicle_type_rates = array();
            foreach ($arrVehicleCharges as $key => $charge) {
                $chargeDetails[$key] = $charge;
                $vehicle_charges = VehicleTypeRates::find()->where(['vehicle_type_id' => $type_id, 'vehicle_charge_id' => $key])->one();
                if (!empty($vehicle_charges)) {
                    $vehicle_type_rates[$key] = $vehicle_charges;
                } else {
                    $vehicle_type_rates[$key] = new VehicleTypeRates();
                }
            }
            if (Yii::$app->request->post()) {
                $arrRequestFields = $_REQUEST['VehicleTypeRates'];
                $postData = Yii::$app->request->post();
                $postData = $postData['VehicleTypeRates'];
                foreach ($postData as $key => $value) {
                    $vehicle_type_rates[$key]->load($value);
                    $vehicle_type_rates[$key]['vehicle_charge_id'] = $key;
                    $vehicle_type_rates[$key]['vehicle_type_id'] = $type_id;
                    $vehicle_type_rates[$key]['normal_charge'] = $value['normal_charge'];
                    $vehicle_type_rates[$key]['peak_time_charge'] =$value['peak_time_charge'];
                    $vehicle_type_rates[$key]->save();

                }
                Yii::$app->session->setFlash('success', Yii::getAlias('@vehicle_type_rates_update'));
                return Common::closeColorBox();
            }
            return $this->render('rates', [
                'snVehicleTypeName' => $snVehicleTypeName->title,
                'vehicle_type_rates' => $vehicle_type_rates,
                'chargeDetails' => $chargeDetails,
                'arrVehicleCharges'=>$arrVehicleCharges
            ]);
       
    }

    /**
     * Finds the VehicleTypes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return VehicleTypes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VehicleTypes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/vehicle-types/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleTypes */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
    </div>
    <div class="block-content collapse in">
<div class="vehicle-types-form span12 common_search">

    <?php $form = ActiveForm::begin(); ?>
<div class="row">
                
     <div class="span3 style_input_width">
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
</div>
 <div class="span3 style_input_width">
    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>
</div>
</div>
<div class="row">
     <div class="span3 style_input_width">
    <?=$form->field($model, 'status')->dropDownList(Yii::$app->params['user_status']);?></div>
</div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</div>
</div>

backend/views/vehicle-types/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleTypesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vehicle-types-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    <div class="row">
    <div class="span3 style_input_width">

    <?= $form->field($model, 'title') ?>
</div>
    <div class="span3 style_input_width">
    <?= $form->field($model, 'description') ?>
</div>
</div>
<div class="row">
    <div class="span3 style_input_width">

     <?=$form->field($model, 'status')->dropDownList(Yii::$app->params['user_status']);?></div>
 </div>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

   <div class="form-group">
        <?=Html::submitButton('Search', ['class' => 'btn btn-primary'])?>
        <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> clear'), Yii::$app->urlManager->createUrl(['vehicle-types/index', "temp" => "clear"]), ['class' => 'btn btn-default'])?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vehicle-types/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleTypes */

$this->title = 'Create Vehicle Type';
$this->params['breadcrumbs'][] = ['label' => 'Manage Vehicle Types', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vehicle-types-create email-format-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vehicle-types/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\components\Common;

/* @var $this yii\web\View */
/* @var $searchModel common\models\VehicleTypesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Vehicle Types';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vehicle-types-index email-format-index">
            <div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Search Here</div>
    </div>
        <div class="block-content collapse in">
        <div class="vehicle-types-form span12">

     <?=Html::a(Yii::t('app', '<i class="icon-filter icon-white"></i> Filter'), "javascript:void(0);", ['class' => 'btn btn-primary open_search']);?>
     <?php if (!empty($_REQUEST['VehicleTypesSearch']) || (!empty($_GET['temp']) && $_GET['temp'] == "clear")) {?>
        <div class="vehicle-types
vehicle-typess-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
<?php } else {?>
    <div class="vehicle-types-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    <?php }?>
</div>
</div>
</div>
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
        <div class="pull-right">
            <?=Html::a(Yii::t('app', '<i class="icon-plus"></i> Add Vehicle Type'), ['create'], ['class' => 'btn btn-success'])?>
            <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> Reset'), Yii::$app->urlManager->createUrl(['vehicle-types/index']), ['class' => 'btn btn-primary'])?>
        </div>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]);  ?>
    <div class="block-content">
        <div class="goodtable">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
           'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

          //  'id',
            'title',
            'description',
           [
            'attribute' => 'status',
            'filterOptions' => ["style" => "width:13%;"],
            'headerOptions' => ["style" => "width:13%;"],
            'contentOptions' => ["style" => "width:13%;"],
            'value' => function ($data) {
                return Yii::$app->params['user_status'][$data->status];
            },
        ],
            //'created_at',
            //'updated_at',

                  [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{update}{add_vehicle_rates}{delete}',
            'buttons' => [
                'update' => function ($url, $model) {
                    $flag = 1;
                    return Common::template_update_button($url, $model, $flag);
                },
                'add_vehicle_rates' => function ($url, $model) {
                    $title = "Add Vehicle Rates";
                    $flag = 5;
                    $url = Yii::$app->urlManager->createUrl(['vehicle-types/add-rates', 'type_id' => $model->id]);
                    return Common::template_update_permission_button($url, $model,$flag);

                },
                'delete' => function ($url, $model) {
                    $flag = 1;
                    $confirmmessage = "Are you sure you want to delete this user?";
                    return Common::template_delete_button($url, $model, $confirmmessage, $flag);
                },

            ],
        ],
        ],
    ]); ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">
$( document ).ready(function() {
    $('.vehicle-types-serach').hide();
        $('.open_search').click(function(){
            $('.vehicle-types-serach').toggle();
        });
    });

</script>

backend/views/vehicle-types/rates.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\web\js\common;
use yii\jui\DatePicker;

$this->title = Yii::t('app', 'Edit Restaurant Working Hours: ' . $snVehicleTypeName);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left users_permission_title"><?= Html::encode($this->title) ?></div>
    </div>

    <div class="portlet-body form block-content collapse in">
        <div class="users-form span12 hours_form">

            <?php $form = ActiveForm::begin(['id' => 'workinghours_form']); ?>
            <?php //Html::checkBox('select_all', false, array('label' => 'Select All', 'class' => 'select_all')) ?>
          
            <?php 
            foreach ($vehicle_type_rates as $key => $weekday) { 

                ?>
           <?php  //$user['support_only']=='1'); ?>            
                <?php //  Html::checkBox("user_permissions[user_id][$snUserId]",false,array('label'=>$user['first_name'].' '.$user['last_name']));  ?>
             
                    
                     <div class="row">
                        <div class="span3">
                            <?= $form->field($weekday, "[$key]vehicle_charge_id")->textInput(['value'=>$arrVehicleCharges[$key],'disabled'=>true]) ?>
                       </div>

                        <div class="span3">
                              <?= $form->field($weekday, "[$key]normal_charge")->textInput(['class'=>"form-control normal_charge_$key normal_charge_common",'id'=>'normal_charge','required'=>"required"]) ?>   
                       </div>
                        <div class="span3">
                            <?php echo $form->field($weekday, "[$key]peak_time_charge")->textInput(['class'=>"form-control peak_time_charge_$key peak_time_charge_common",'id'=>'peak_time_charge',"required"=>"required"]) ?>  
                       </div>
                   </div>       
            <?php } ?>
        

            <div class="form-group form-actions">
                <?= Html::submitButton('Save', ['class' => 'btn btn-success submitButton'/* , 'onClick' => 'javascript:console.log($(".users-form .userfieldsShow"));return false;' */]) ?>
                <?= Html::a(Yii::t('app', 'Cancel'), 'javascript:void(0)', ['class' => 'btn default btn-success', 'onClick' => 'parent.jQuery.colorbox.close();']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
  
    
</script>

backend/views/vehicle-types/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleTypes */

$this->title = 'Update Vehicle Types: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Vehicle Types', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="vehicle-types-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vehicle-types/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleTypes */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Vehicle Types', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="vehicle-types-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description',
            'seat_count',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>