common/models/PeakTimes.php
<?php

namespace common\models;

class PeakTimes extends \common\models\base\PeakTimesBase
{
     public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->setAttribute('created_at', date('Y-m-d H:i:s'));
        }
        $this->setAttribute('updated_at', date('Y-m-d H:i:s'));

        return parent::beforeSave($insert);
    }

    public function rules()
{
        return [
            [['name', 'start_time', 'end_time'], 'required'],
            [['name', 'start_time', 'end_time'],'filter', 'filter' => 'trim'],
            [['start_time', 'end_time', 'created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
        ];
}
}

backend/controllers/PeakTimesController.php
<?php
  
namespace backend\controllers;

use Yii;
use common\models\PeakTimes;
use common\models\PeakTimesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\components\AdminCoreController;

  
/**
 * PeakTimesController implements the CRUD actions for PeakTimes model.
 */
class PeakTimesController extends AdminCoreController
{
    /**
     * {@inheritdoc}
     */
   /* public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }*/

    /**
     * Lists all PeakTimes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PeakTimesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PeakTimes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PeakTimes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PeakTimes();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $postData = Yii::$app->request->post();
             $model->start_time = date("H:i:s", strtotime($postData['PeakTimes']['start_time']));
            $model->end_time = date("H:i:s", strtotime($postData['PeakTimes']['end_time']));
            $model->save(false);
            Yii::$app->session->setFlash('success', Yii::getAlias('@peak_times_create'));
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing PeakTimes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $postData = Yii::$app->request->post();
             $model->start_time = date("H:i:s", strtotime($postData['PeakTimes']['start_time']));
            $model->end_time = date("H:i:s", strtotime($postData['PeakTimes']['end_time']));
            $model->save(false);
            Yii::$app->session->setFlash('success', Yii::getAlias('@peak_times_update'));
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing PeakTimes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('success', Yii::getAlias('@peak_times_delete'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the PeakTimes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PeakTimes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PeakTimes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/peak-times/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PeakTimes */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
    </div>
    <div class="block-content collapse in">
<div class="peak-times-form span12 common_search">

    <?php $form = ActiveForm::begin(); ?>
<div class="row">
                
     <div class="span3 style_input_width">
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
</div>
</div>

<div class="row">
     <div class="span3 style_input_width">
    <?php // $form->field($model, 'start_time')->textInput() ?>
    
   <?= $form->field($model, 'start_time')->textInput(['class'=>'form-control end_time','value'=>$model->start_time]); ?>
               
      </div></div>
      <div class="row">
     <div class="span3 style_input_width">       
   <?= $form->field($model, 'end_time')->textInput(['class'=>'form-control end_time','value'=>$model->end_time]); ?>
</div>
</div>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">
  
$(document).ready(function(){
    $('.start_time').timepicker();
    $('.end_time').timepicker();
});
</script>

backend/views/peak-times/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PeakTimesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="peak-times-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
 <div class="row">
    <div class="span3 style_input_width">

    <?= $form->field($model, 'name') ?>
</div>
</div>
<div class="row">
    <div class="span3 style_input_width">
      <?= $form->field($model, 'start_time')->textInput(['class'=>'form-control end_time','value'=>$model->start_time]); ?>
</div>
</div>
<div class="row">
    <div class="span3 style_input_width">
   <?= $form->field($model, 'end_time')->textInput(['class'=>'form-control end_time','value'=>$model->end_time]); ?>
</div>
</div>

    <?php // echo $form->field($model, 'updated_at') ?>

 <div class="form-group">
        <?=Html::submitButton('Search', ['class' => 'btn btn-primary'])?>
        <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> clear'), Yii::$app->urlManager->createUrl(['peak-times/index', "temp" => "clear"]), ['class' => 'btn btn-default'])?>
    </div>


    <?php ActiveForm::end(); ?>

</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">
  
$(document).ready(function(){
    $('.start_time').timepicker();
    $('.end_time').timepicker();
});
</script>

backend/views/peak-times/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\PeakTimes */

$this->title = 'Create Peak Times';
$this->params['breadcrumbs'][] = ['label' => 'Manage Peak Times', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="peak-times-create email-format-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/peak-times/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\components\Common;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PeakTimesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Peak Times';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="peak-times-index email-format-index">

        <div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Search Here</div>
    </div>
        <div class="block-content collapse in">
        <div class="peak-times-form span12">

     <?=Html::a(Yii::t('app', '<i class="icon-filter icon-white"></i> Filter'), "javascript:void(0);", ['class' => 'btn btn-primary open_search']);?>
     <?php if (!empty($_REQUEST['PeakTimesSearch']) || (!empty($_GET['temp']) && $_GET['temp'] == "clear")) {?>
        <div class="peak-times
peak-timess-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
<?php } else {?>
    <div class="peak-times-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    <?php }?>
</div>
</div>
</div>
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
        <div class="pull-right">
            <?=Html::a(Yii::t('app', '<i class="icon-plus"></i> Add Peak Times'), ['create'], ['class' => 'btn btn-success'])?>
            <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> Reset'), Yii::$app->urlManager->createUrl(['peak-times/index']), ['class' => 'btn btn-primary'])?>
        </div>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]);  ?>
    <div class="block-content">
        <div class="goodtable">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
         'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

         //   'id',
            'name',
            'start_time',
            'end_time',
           // 'created_at',
            //'updated_at',

                 [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{update}{delete}',
            'buttons' => [
                'update' => function ($url, $model) {
                    $flag = 1;
                    return Common::template_update_button($url, $model, $flag);
                },
                'delete' => function ($url, $model) {
                    $flag = 1;
                    $confirmmessage = "Are you sure you want to delete this user?";
                    return Common::template_delete_button($url, $model, $confirmmessage, $flag);
                },

            ],
        ],
        ],
    ]); ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">
$( document ).ready(function() {
    $('.peak-times-serach').hide();
        $('.open_search').click(function(){
            $('.peak-times-serach').toggle();
        });
    });

</script>

backend/views/peak-times/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\PeakTimes */

$this->title = 'Update Peak Times: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Manage Peak Times', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="peak-times-update email-format-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/peak-times/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\PeakTimes */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Peak Times', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="peak-times-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'start_time',
            'end_time',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>