common/models/VehicleDetails.php
<?php

namespace common\models;

class VehicleDetails extends \common\models\base\VehicleDetailsBase
{
     public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->setAttribute('created_at', date('Y-m-d H:i:s'));
        }
        $this->setAttribute('updated_at', date('Y-m-d H:i:s'));

        return parent::beforeSave($insert);
    }
}

backend/controllers/VehicleDetailsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\VehicleDetails;
use common\models\VehicleDetailsSearch;
use backend\components\AdminCoreController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\components\Common;
use common\models\Users;
use common\models\EmailFormat;
use common\models\NotificationList;
use common\models\DeviceDetails;



/**
 * VehicleDetailsController implements the CRUD actions for VehicleDetails model.
 */
class VehicleDetailsController extends AdminCoreController
{
    /**
     * {@inheritdoc}
     */
   /* public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }*/

    /**
     * Lists all VehicleDetails models.
     * @return mixed
     */
    public function actionIndex($user_id)
    {
        $searchModel = new VehicleDetailsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single VehicleDetails model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new VehicleDetails model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VehicleDetails();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing VehicleDetails model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing VehicleDetails model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    public function actionApproveVehicle($vehicle_id)
    {
        $this->layout = 'popup';
        $vehicleModel = VehicleDetails::find()->where(['id' => $vehicle_id])->one();
        if (!empty(Yii::$app->request->post()) && !empty($vehicleModel)) {

            $postData = Yii::$app->request->post();
            $vehicleModel->is_approve = $postData['VehicleDetails']['is_approve'];
            $vehicleModel->admin_message = $postData['VehicleDetails']['admin_message'];
           if($vehicleModel->save(false)){
             $user_id = $vehicleModel->user_id;
            $deviceModel = DeviceDetails::find()->select('device_tocken,type')->where(['user_id' => $user_id])->one();
                $device_tocken = !empty($deviceModel) ? $deviceModel->device_tocken : "";
                $type = !empty($deviceModel) ? $deviceModel->type : "";
                if (!empty($type) && $type == Yii::$app->params['device_type']['android']) {
                    $title = "Vehicle Status Notification";
                    $body = "Your Vehicle is " . Yii::$app->params['is_approve_vehicle'][$vehicleModel->is_approve]." by admin.";
                    $status = Common::push_notification_android($device_tocken, $title, $body);
                    if ($status) {
                        $NotificationListModel = new NotificationList();
                        $NotificationListModel->user_id = $user_id;
                        $NotificationListModel->title = $title;
                        $NotificationListModel->body = $body;
                        $NotificationListModel->status = 1;
                        $NotificationListModel->save(false);
                    }
                }
                $emailformatemodel = EmailFormat::findOne(["title" => 'vehicle_status', "status" => '1']);
                    if ($emailformatemodel) {
                        $user = Users::findOne($user_id);
                        //create template file
                        $AreplaceString = array('{driver_name}' => $user->first_name." ".$user->last_name,'{vehicle_name}'=>$vehicleModel->name,'{is_approve}'=>Yii::$app->params['is_approve_vehicle'][$vehicleModel->is_approve],'{admin_message}'=>$vehicleModel->admin_message);

                        $body = Common::MailTemplate($AreplaceString, $emailformatemodel->body);
                        $ssSubject = $emailformatemodel->subject;
                        //send email for new generated password
                        $ssResponse = Common::sendMail($user->email, Yii::$app->params['adminEmail'], $ssSubject, $body);


           }
            Yii::$app->session->setFlash('success', Yii::getAlias('@vehicle_update_message'));
            return Common::closeColorBox();

        }
    }
        return $this->render('approve_vehicle', [
            'vehicleModel' => $vehicleModel,
        ]);
}


    /**
     * Finds the VehicleDetails model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return VehicleDetails the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VehicleDetails::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/vehicle-details/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleDetails */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vehicle-details-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'vehicle_type_id')->textInput() ?>

    <?= $form->field($model, 'seat_capacity')->textInput() ?>

    <?= $form->field($model, 'vehicle_registration_no')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'vehicle_image_front')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'vehicle_image_back')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'driver_license_image_front')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'driver_license_image_back')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'vehicle_registration_image_front')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'vehicle_registration_image_back')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vehicle-details/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleDetailsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vehicle-details-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'vehicle_type_id') ?>

    <?= $form->field($model, 'seat_capacity') ?>

    <?php // echo $form->field($model, 'vehicle_registration_no') ?>

    <?php // echo $form->field($model, 'vehicle_image_front') ?>

    <?php // echo $form->field($model, 'vehicle_image_back') ?>

    <?php // echo $form->field($model, 'driver_license_image_front') ?>

    <?php // echo $form->field($model, 'driver_license_image_back') ?>

    <?php // echo $form->field($model, 'vehicle_registration_image_front') ?>

    <?php // echo $form->field($model, 'vehicle_registration_image_back') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vehicle-details/approve_vehicle.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Approve Product: ' . $vehicleModel->name);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left users_permission_title"><?=Html::encode($this->title)?></div>
    </div>

    <div class="portlet-body form block-content collapse in">
        <div class="users-form span12 hours_form">
            <?php $form = ActiveForm::begin(['id' => 'approve_driver_form']);?>
            <?php //Html::checkBox('select_all', false, array('label' => 'Select All', 'class' => 'select_all')) ?>
                            <?=$form->field($vehicleModel, "is_approve")->dropDownList(Yii::$app->params['is_approve_vehicle']); ?>

                             <?=$form->field($vehicleModel, "admin_message")->textArea(['required' => "required"]); ?>
                       </div>
                   </div>

                   </div>

            <div class="form-group form-actions">
                <?=Html::submitButton('Save', ['class' => 'btn btn-success submitButton' /* , 'onClick' => 'javascript:console.log($(".users-form .userfieldsShow"));return false;' */])?>
                <?=Html::a(Yii::t('app', 'Cancel'), 'javascript:void(0)', ['class' => 'btn default btn-success', 'onClick' => 'parent.jQuery.colorbox.close();'])?>
            </div>
            <?php ActiveForm::end();?>

<script type="text/javascript">

</script>

backend/views/vehicle-details/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleDetails */

$this->title = 'Create Vehicle Details';
$this->params['breadcrumbs'][] = ['label' => 'Vehicle Details', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vehicle-details-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vehicle-details/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\components\Common;
/* @var $this yii\web\View */
/* @var $searchModel common\models\VehicleDetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Vehicle Details : '.Common::get_user_name($_GET['user_id']);
$this->params['breadcrumbs'][] = ['label' => 'Manage Users', 'url' => ['users/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<style type="text/css">


    
.nav-list li:nth-child(2), .nav-list li:nth-child(2) a:hover{background: #006dcc;}
.nav-list li:nth-child(2) span, .nav-list li:nth-child(2) span:hover{color: #fff!important;}

  /* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
}

/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}

  .modal-body {
    position:relative; /* This avoids whatever it's absolute inside of it to go off the container */
    height: 250px; /* let's imagine that your login box height is 250px . This height needs to be added, otherwise .img-responsive will be like "Oh no, I need to be vertically aligned?! but from which value I need to be aligned??" */
}
.img-responsive {
   
    left:50%;
    top:50%;
    margin-top:-25px; /* This needs to be half of the height */
    margin-left:-25px; /* This needs to be half of the width */
}
</style>
<div class="vehicle-details-index email-format-index">

    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]);  ?>
    <div class="block-content">
        <div class="goodtable">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
         'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

          //  'id',
          //  'user_id',
            'name',
           // 'vehicle_type_id',
            [
            'attribute' => 'vehicle_type_id',
            'value' => function ($data){
                return !empty($data->vehicle_type_id) ? $data->vehicleType->title : '-';
            },
        ],
            'seat_capacity',
            'vehicle_registration_no',
        [
            'attribute' => 'vehicle_image_front',
                 'format' => 'html',
             'value' => function ($data) {
                if (!empty($data->vehicle_image_front)) {
                $vehicle_image_front = Yii::$app->params['root_url'] . '/' . "uploads/driver_images/" . $data->vehicle_image_front;
                return Html::img($vehicle_image_front, ['alt'=>'Vehicle Image Front','width'=>'250','height'=>'100','class'=>"myImg"]);
                } else {
                    return "-";
                }
            },
        ],
        [
            'attribute' => 'vehicle_image_back',
                 'format' => 'html',
             'value' => function ($data) {
                if (!empty($data->vehicle_image_back)) {
                $vehicle_image_back = Yii::$app->params['root_url'] . '/' . "uploads/driver_images/" . $data->vehicle_image_back;
                return Html::img($vehicle_image_back, ['alt'=>'Vehicle Image Back','width'=>'250','height'=>'100','class'=>"myImg"]);
                } else {
                    return "-";
                }
            },
        ],
            [
            'attribute' => 'driver_license_image_front',
            'format' => 'html',
            'value' => function ($data) {
                if (!empty($data->driver_license_image_front)) {
                $driver_license_image_front = Yii::$app->params['root_url'] . '/' . "uploads/driver_images/" . $data->driver_license_image_front;
                return Html::img($driver_license_image_front, ['alt'=>'Driver Licence Image Front','width'=>'250','height'=>'100','class'=>"myImg"]);
                } else {
                    return "-";
                }
            },
        ],
         [
            'attribute' => 'driver_license_image_back',
            'format' => 'html',
             'value' => function ($data) {
                if (!empty($data->driver_license_image_back)) {
                $driver_license_image_back = Yii::$app->params['root_url'] . '/' . "uploads/driver_images/" . $data->driver_license_image_back;
                return Html::img($driver_license_image_back, ['alt'=>'Driver Licence Image Back','width'=>'250','height'=>'100','class'=>"myImg"]);
                } else {
                    return "-";
                }
            },
        ],
             [
            'attribute' => 'vehicle_registration_image_front',
              'format' => 'html',
             'value' => function ($data) {
                if (!empty($data->vehicle_registration_image_front)) {
                $vehicle_registration_image_front = Yii::$app->params['root_url'] . '/' . "uploads/driver_images/" . $data->vehicle_registration_image_front;
                return Html::img($vehicle_registration_image_front, ['alt'=>'Vehicle Registration Image Front','width'=>'250','height'=>'100','class'=>"myImg"]);
                } else {
                    return "-";
                }
            },
        ],
             [
            'attribute' => 'vehicle_registration_image_back',
             'format' => 'html',
             'value' => function ($data) {
                if (!empty($data->vehicle_registration_image_back)) {
                $vehicle_registration_image_back = Yii::$app->params['root_url'] . '/' . "uploads/driver_images/" . $data->vehicle_registration_image_back;
                return Html::img($vehicle_registration_image_back, ['alt'=>'Vehicle Registration Image Back','width'=>'250','height'=>'100','class'=>"myImg"]);
                } else {
                    return "-";
                }
            },
        ],
            //'status',
            //'created_at',
            //'updated_at',

         [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{approve_vehicle}',
            'buttons' => [
           'approve_vehicle' => function ($url, $model) {
                    $title = "Approve Vehicle";
                    $flag = 5;
                    $url = Yii::$app->urlManager->createUrl(['vehicle-details/approve-vehicle', 'vehicle_id' => $model->id]);
                    return Common::template_approve_driver($url, $model, $title, $flag);

                },

            ],
        ],
        ],
    ]); ?>
        </div>
    </div>
</div>

<!-- The Modal -->
  


<!-- 
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="img-fluid" id="img01">
  <div id="caption"></div>
</div> -->

<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="Model-Center">
          <img class="img-fluid" id="img01">
  <div id="caption"></div>
        </div>
        
        <!-- Modal footer -->
        
      </div>
    </div>
  </div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">



$( document ).ready(function() {
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
$(".myImg").on('click', function(event){
  modal.style.display = "block";
  modalImg.src = this.src;
  captionText.innerHTML = this.alt;
});

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
  modal.style.display = "none";
}

    });
</script>

backend/views/vehicle-details/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleDetails */

$this->title = 'Update Vehicle Details: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Vehicle Details', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="vehicle-details-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vehicle-details/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\VehicleDetails */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Vehicle Details', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="vehicle-details-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'name',
            'vehicle_type_id',
            'seat_capacity',
            'vehicle_registration_no',
            'vehicle_image_front',
            'vehicle_image_back',
            'driver_license_image_front',
            'driver_license_image_back',
            'vehicle_registration_image_front',
            'vehicle_registration_image_back',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>